development:
  sessions:
    default:
      options:
      database: subout
      username: heroku
      password: sub0utd3v
      hosts: 
        - alex.mongohq.com:10029
production:
  sessions:
    default:
      options:
        database: subout
        username: heroku
        password: sub0utd3v
        hosts: 
          - alex.mongohq.com:10029
